name: CI/CD

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  PRIMARY_NODE_VERSION: 20
  # This increases the verbosity of the logs for everything, including Nx Cloud, but might surface more info about recent lint failures
  NX_VERBOSE_LOGGING: true

defaults:
  run:
    shell: bash

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request'}}

    steps:
      - name: Checkout [${{github.ref_name}}]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - name: Lint
        run: npx nx affected -t lint
      - name: Test
        run: npx nx affected -t test
      - name: Build
        run: npx nx affected -t build
      - name: Check if backend is affected
        run: echo 'Backend affected $(npx nx affected:apps --base=origin/development --head=$GITHUB_SHA)'
        id: affected-backend

  PR:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Commit lint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Lint
        run: npx nx affected -t lint
      - name: Test
        run: npx nx affected -t test
      - name: Build
        run: npx nx affected -t build
